<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_Field</name>
   <tag></tag>
   <elementGuidId>3e083c7c-c533-44c6-92db-bf1324a9515e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auth_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03f935bc-e93d-4ed7-9fa6-1cb0978923f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:shadow-outline my-2 w-full appearance-none rounded-lg border py-3 px-3.5 text-xs font-normal leading-tight text-gray-700 focus:outline-none lg:text-sm</value>
      <webElementGuid>d6f2fb26-05e5-4caa-aa79-3c742f221630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79e97c0e-cbcb-47d4-9893-344fbc332a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth_email</value>
      <webElementGuid>34d49093-6ccd-4da4-9713-faff91b544a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth_email&quot;)</value>
      <webElementGuid>6d4281a0-704b-4ebd-95f8-b178c029b43e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auth_email']</value>
      <webElementGuid>cb48b095-e55f-4a4d-b962-10764ef4a0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div/input</value>
      <webElementGuid>61cb7c78-580f-40d3-909f-8348c5050afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d79320b-1198-4ded-826b-36045be24d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'auth_email']</value>
      <webElementGuid>9d68f228-48cc-4064-acc3-de35a4ce1bda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
