<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password_Field</name>
   <tag></tag>
   <elementGuidId>9312d441-934d-4252-952b-91c76a018524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auth_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aecde39c-528b-4be5-9ed3-01ed9e934c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth_password</value>
      <webElementGuid>038df20c-1d6d-4de1-ac1e-65b428d125fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:shadow-outline my-2 w-full appearance-none rounded-lg border py-3 px-3.5 text-xs font-normal leading-tight text-gray-700 focus:outline-none lg:text-sm</value>
      <webElementGuid>97ec2c81-0000-46e0-acb2-7f9640ebf5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fd5ba195-4596-4f24-9b90-e65992ac0f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth_password&quot;)</value>
      <webElementGuid>0e9011e0-5ce2-4589-9872-49ef4c8e2bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>8e4973c3-4bc6-4e95-a98d-96f054f09d93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auth_password']</value>
      <webElementGuid>5d228d92-14f6-4e57-9751-5074a163f0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div[2]/input</value>
      <webElementGuid>4221e7fa-ba16-4dc2-83fa-134ef934902c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8c40aa3e-e917-4e18-9037-9d8151d5d5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'auth_password' and @type = 'password']</value>
      <webElementGuid>57f54657-fbf6-4466-b98c-de2ba432f3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'auth_password' and @type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>ac61d76b-55ce-474e-a273-3727d6127369</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
